In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("binary_titanic.csv")
df.fillna(df.mean(), inplace = True)
df.head()

PassengerId  Survived  Pclass  \
0            1         1       3   
1            2         2       1   
2            3         2       3   
3            4         2       1   
4            5         1       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    2  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    2  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [5]:
arr = np.asarray(df)
N,D = arr.shape
#making feature matrix
X1 = arr[:,2].reshape(N,1)
X2 = arr[:,5].reshape(N,1)
X3 = arr[:,9].reshape(N,1)
X = np.hstack((X1,X2,X3))
X

array([[3, 22.0, 7.25],
       [1, 38.0, 71.2833],
       [3, 26.0, 7.925],
       ...,
       [3, 29.69911764705882, 23.45],
       [1, 26.0, 30.0],
       [3, 32.0, 7.75]], dtype=object)

In [6]:
#Dimensions
N,D = X.shape
M = 5 #num hidden nodes
K = 2 #num output nodes

#weight matrixes
w = np.random.randn(D*M).reshape(D,M)
v = np.random.randn(M*K).reshape(M,K)

#Biases
b_temp = np.random.randn(M).reshape(1,M)
ones = np.ones(N).reshape(N,1)
b = np.dot(ones,b_temp)

c_temp = np.random.randn(K).reshape(1,K)
ones = np.ones(N).reshape(N,1)
c = np.dot(ones,c_temp)

In [7]:
z = np.dot(X,w) + b
Sigma = 1/(1 + np.exp(-z.astype(float)))
Y = np.exp(np.dot(Sigma,v) + c)


In [6]:
targets = arr[:,1].reshape(891,1)
targets

array([[1],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [2],
    

In [17]:
class neural_net_one_hidden:
    def __init__(self):
        pass 

    def back_propogation(iterations, learning_rate, targets, smoothing_parameter, num_of_hidden_nodes, num_of_output_nodes):
        
        np.random.seed(1)
        # Dimensions 
        N, D = X.shape
        M = num_of_hidden_nodes
        K = num_of_output_nodes
        
        # Inital Weights
        w = np.random.randn(D * M).reshape(D, M)
        v = np.random.randn(M * K).reshape(M, K)
        
        # Initial Biases 
        b_1 = np.random.randn(M).reshape(1, M)
        ones = np.ones(N).reshape(N, 1)
        b = np.dot(ones, b_1).astype(object)
        c_1 = np.random.randn(K).reshape(1, K)
        c = np.dot(ones, c_1).astype(object)
        
        #Targets after one hot encoding
        zeros = np.zeros(N*K).reshape(N,K)
        T = np.hstack((targets,zeros))
        
        for i in range(N):
            index_value = T[i,0]
            T[i, int(index_value)] = 1
        T = np.delete(T, 0, axis = 1)
        
        # Gradient descent loop 
        for i in range(iterations):
            # Feedforward
            Z = (1)/(1 + np.exp(-(np.dot(X.astype(float), w.astype(float)) + b.astype(float))))
            Y = np.dot(Z.astype(float), v.astype(float)) + c.astype(float)
            S, J = Y.shape
            for i in range(S):
                Y[i, :] = np.exp(Y[i, :])/(np.exp(Y[i, :]).sum())

            # Gradients 
            partial_v = Z.T.dot(T - Y)
            first = np.dot((T - Y), v.T)
            Second = np.dot(first.T, Z)
            Third = np.dot(Second, (1 - Z).T)
            partial_w = np.dot(X.T, first * Z * (1-Z))
            partial_c = (T - Y).sum(axis=0)
            partial_b = ((T - Y).dot(v.T) * Z * (1 - Z)).sum(axis=0)
            
            
            # Cost 
            total = -np.dot(T.T, np.log(Y))
            cost = total.sum()
            
            #Gradient Descent 
            v += learning_rate * (partial_v.astype(float))# - smoothing_parameter*v)
            w += learning_rate * (partial_w.astype(float))# - smoothing_parameter * w)
            b += learning_rate * partial_b.astype(float)
            c += learning_rate * partial_c.astype(float)
            
            
            # Accuracy 
        
        #Accuracy = np.mean(np.round(Y) == T) #THis way of doing it yields the same result
        
        n_correct = 0
        n_total = 0
        for i in range(len(Y)):
            for j in range(len(Y[0])):
                n_total += 1
                if np.round(Y[i,j]) == T[i,j]:
                    n_correct += 1
        Accuracy = float(n_correct) / float(n_total)
        
        #print("The weights after {} iterations of gradient descent are w = {} \n v = {}.".format(iterations, w, v))
        #print("The biases after {} iterations of gradient descent are b = {} \n c = {}.".format(iterations, b, c))
        #print ("{}% of the targets match the predictions".format(Accuracy * 100))
        print(((T - Y).dot(v.T)).shape, Z.shape)
        return type(Z), type(T), type(Y), type(v), ((T - Y).dot(v.T)).shape, Z.shape
    
        

In [18]:
neural_net_one_hidden.back_propogation(1,0.0001,targets,0.0001,M,K)

(891, 5) (891, 5)


(numpy.ndarray,
 numpy.ndarray,
 numpy.ndarray,
 numpy.ndarray,
 (891, 5),
 (891, 5))

In [10]:
# Gradient Descent 
            #v += (learning_rate * partial_v - smoothing_parameter*v)
            #w += (learning_rate * partial_w - smoothing_parameter * w)
            #b += learning_rate * partial_b
            #c += learning_rate * partial_c

In [19]:
# backpropagation example for deep learning in python class.
# with sigmoid activation
#
# the notes for this class can be found at: 
# https://deeplearningcourses.com/c/data-science-deep-learning-in-python
# https://www.udemy.com/data-science-deep-learning-in-python
from __future__ import print_function, division
from builtins import range
# Note: you may need to update your version of future
# sudo pip install -U future

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1)

def forward(X, W1, b1, W2, b2):
    Z = 1 / (1 + np.exp(-X.dot(W1) - b1))
    A = Z.dot(W2) + b2
    expA = np.exp(A)
    Y = expA / expA.sum(axis=1, keepdims=True)
    return Y, Z


# determine the classification rate
# num correct / num total
def classification_rate(Y, P):
    n_correct = 0
    n_total = 0
    for i in range(len(Y)):
        n_total += 1
        if Y[i] == P[i]:
            n_correct += 1
    return float(n_correct) / n_total


def derivative_w2(Z, T, Y):
    N, K = T.shape
    M = Z.shape[1] # H is (N, M)

    # # slow
    # ret1 = np.zeros((M, K))
    # for n in xrange(N):
    #     for m in xrange(M):
    #         for k in xrange(K):
    #             ret1[m,k] += (T[n,k] - Y[n,k])*Z[n,m]

    # # a bit faster - let's not loop over m
    # ret2 = np.zeros((M, K))
    # for n in xrange(N):
    #     for k in xrange(K):
    #         ret2[:,k] += (T[n,k]* - Y[n,k])*Z[n,:]

    # assert(np.abs(ret1 - ret2).sum() < 0.00001)

    # # even faster  - let's not loop over k either
    # ret3 = np.zeros((M, K))
    # for n in xrange(N): # slow way first
    #     ret3 += np.outer( Z[n], T[n] - Y[n] )

    # assert(np.abs(ret1 - ret3).sum() < 0.00001)

    # fastest - let's not loop over anything
    ret4 = Z.T.dot(T - Y)
    # assert(np.abs(ret1 - ret4).sum() < 0.00001)

    return ret4


def derivative_w1(X, Z, T, Y, W2):
    N, D = X.shape
    M, K = W2.shape

    # slow way first
    # ret1 = np.zeros((X.shape[1], M))
    # for n in xrange(N):
    #     for k in xrange(K):
    #         for m in xrange(M):
    #             for d in xrange(D):
    #                 ret1[d,m] += (T[n,k] - Y[n,k])*W2[m,k]*Z[n,m]*(1 - Z[n,m])*X[n,d]

    # fastest
    dZ = (T - Y).dot(W2.T) * Z * (1 - Z)
    ret2 = X.T.dot(dZ)
    print(type(Z))
    #print(ret2.shape, T.shape, W2.shape, Z.shape, X.shape)
    #print(ret2)
    # assert(np.abs(ret1 - ret2).sum() < 0.00001)

    return ret2


def derivative_b2(T, Y):
    print((T - Y).sum(axis=0))
    return (T - Y).sum(axis=0)


def derivative_b1(T, Y, W2, Z):
    print(((T - Y).dot(W2.T) * Z * (1 - Z)).sum(axis=0))
    return ((T - Y).dot(W2.T) * Z * (1 - Z)).sum(axis=0)


def cost(T, Y):
    tot = T * np.log(Y)
    return tot.sum()


def main():
    # create the data
    Nclass = 500
    D = 2 # dimensionality of input
    M = 3 # hidden layer size
    K = 3 # number of classes

    X1 = np.random.randn(Nclass, D) + np.array([0, -2])
    X2 = np.random.randn(Nclass, D) + np.array([2, 2])
    X3 = np.random.randn(Nclass, D) + np.array([-2, 2])
    X = np.vstack([X1, X2, X3])

    Y = np.array([0]*Nclass + [1]*Nclass + [2]*Nclass)
    N = len(Y)
    # turn Y into an indicator matrix for training
    T = np.zeros((N, K))
    for i in range(N):
        T[i, Y[i]] = 1

    # let's see what it looks like
    plt.scatter(X[:,0], X[:,1], c=Y, s=100, alpha=0.5)
    plt.show()

    # randomly initialize weights
    W1 = np.random.randn(D, M)
    b1 = np.random.randn(M)
    W2 = np.random.randn(M, K)
    b2 = np.random.randn(K)

    learning_rate = 1e-3
    costs = []
    for epoch in range(1000):
        output, hidden = forward(X, W1, b1, W2, b2)
        if epoch % 100 == 0:
            c = cost(T, output)
            P = np.argmax(output, axis=1)
            r = classification_rate(Y, P)
            print("cost:", c, "classification_rate:", r)
            costs.append(c)

        # this is gradient ASCENT, not DESCENT
        # be comfortable with both!
        # oldW2 = W2.copy()
        W2 += learning_rate * derivative_w2(hidden, T, output)
        b2 += learning_rate * derivative_b2(T, output)
        W1 += learning_rate * derivative_w1(X, hidden, T, output, W2)
        b1 += learning_rate * derivative_b1(T, output, W2, hidden)

    plt.plot(costs)
    plt.show()


if __name__ == '__main__':
    main()

<Figure size 640x480 with 1 Axes>

cost: -3147.180844402328 classification_rate: 0.26866666666666666
[-173.79758596 -238.15389734  411.9514833 ]
<class 'numpy.ndarray'>
[-21.74950507 -89.46241903 -11.25357122]
[  23.79084452 -319.68169317  295.89084866]
<class 'numpy.ndarray'>
[-13.83703323   2.25531505 -70.8902739 ]
[  23.04058225 -141.08062096  118.04003872]
<class 'numpy.ndarray'>
[ -8.11752613  26.45118931 -48.53984306]
[ 63.98886615 -86.761199    22.77233285]
<class 'numpy.ndarray'>
[ -8.96751386  46.8610866  -41.0670148 ]
[ 61.40043498 -64.35416838   2.9537334 ]
<class 'numpy.ndarray'>
[-10.09841976  49.05611335 -34.29701173]
[ 50.10905532 -51.06255556   0.95350024]
<class 'numpy.ndarray'>
[-10.41384434  45.6111801  -30.04361209]
[ 39.9054577  -41.95850165   2.05304394]
<class 'numpy.ndarray'>
[-10.24735052  41.76090684 -27.71970948]
[ 31.96831717 -36.00560355   4.03728638]
<class 'numpy.ndarray'>
[ -9.86280478  38.7309996  -26.70905041]
[ 25.83540252 -31.99251506   6.15711254]
<class 'numpy.ndarray'>
[ -9.3828599

[ 1.71775052 -4.02800155  2.31025102]
<class 'numpy.ndarray'>
[-0.4783785   3.70962517 -3.00243911]
[ 1.70578047 -3.9934134   2.28763293]
<class 'numpy.ndarray'>
[-0.45723658  3.65928391 -2.95539325]
[ 1.69404657 -3.95944249  2.26539592]
<class 'numpy.ndarray'>
[-0.43654693  3.60998542 -2.9092384 ]
[ 1.68254188 -3.92607302  2.24353114]
<class 'numpy.ndarray'>
[-0.41629773  3.56169989 -2.86395115]
[ 1.67125976 -3.89328974  2.22202998]
<class 'numpy.ndarray'>
[-0.39647759  3.51439856 -2.81950889]
[ 1.66019379 -3.8610779   2.20088411]
<class 'numpy.ndarray'>
[-0.37707544  3.4680537  -2.77588978]
[ 1.64933779 -3.82942322  2.18008542]
<class 'numpy.ndarray'>
[-0.35808059  3.42263853 -2.7330727 ]
[ 1.63868583 -3.79831188  2.15962605]
<class 'numpy.ndarray'>
[-0.33948267  3.3781272  -2.69103727]
[ 1.62823216 -3.76773052  2.13949835]
<class 'numpy.ndarray'>
[-0.32127164  3.33449474 -2.64976376]
[ 1.61797128 -3.73766619  2.11969491]
<class 'numpy.ndarray'>
[-0.30343779  3.29171707 -2.60923309]


[ 1.03535228 -1.97838574  0.94303346]
<class 'numpy.ndarray'>
[ 0.52389215  0.99588249 -0.37186288]
[ 1.03309258 -1.97145524  0.93836266]
<class 'numpy.ndarray'>
[ 0.52560328  0.98757862 -0.36404245]
[ 1.03085285 -1.96458542  0.93373257]
<class 'numpy.ndarray'>
[ 0.52727691  0.97935147 -0.35630587]
[ 1.02863283 -1.9577755   0.92914267]
<class 'numpy.ndarray'>
[ 0.5289136   0.97119997 -0.34865206]
[ 1.02643226 -1.95102472  0.92459246]
<class 'numpy.ndarray'>
[ 0.53051387  0.96312308 -0.34107994]
[ 1.02425091 -1.94433235  0.92008144]
<class 'numpy.ndarray'>
[ 0.53207825  0.95511975 -0.33358848]
[ 1.02208852 -1.93769764  0.91560912]
<class 'numpy.ndarray'>
[ 0.53360727  0.94718898 -0.32617663]
[ 1.01994488 -1.93111988  0.911175  ]
<class 'numpy.ndarray'>
[ 0.53510141  0.93932976 -0.31884339]
[ 1.01781973 -1.92459835  0.90677862]
<class 'numpy.ndarray'>
[ 0.5365612   0.93154113 -0.31158775]
[ 1.01571285 -1.91813237  0.90241951]
<class 'numpy.ndarray'>
[ 0.5379871   0.92382212 -0.30440874]


<class 'numpy.ndarray'>
[0.55419439 0.29913813 0.20805359]
[ 0.84286042 -1.38611427  0.54325385]
<class 'numpy.ndarray'>
[0.55358266 0.29598563 0.21009174]
[ 0.84198782 -1.38343762  0.5414498 ]
<class 'numpy.ndarray'>
[0.55296496 0.29285068 0.21211035]
[ 0.84111976 -1.38077552  0.53965576]
<class 'numpy.ndarray'>
[0.55234139 0.28973312 0.21410963]
[ 0.8402562  -1.37812785  0.53787165]
<class 'numpy.ndarray'>
[0.55171202 0.28663283 0.21608973]
[ 0.83939711 -1.3754945   0.53609739]
<class 'numpy.ndarray'>
[0.55107693 0.28354966 0.21805083]
[ 0.83854244 -1.37287533  0.53433289]
<class 'numpy.ndarray'>
[0.55043621 0.28048346 0.21999311]
[ 0.83769214 -1.37027022  0.53257808]
<class 'numpy.ndarray'>
[0.54978993 0.27743411 0.22191672]
cost: -116.9091029167447 classification_rate: 0.9686666666666667
[ 0.83684618 -1.36767906  0.53083288]
<class 'numpy.ndarray'>
[0.54913817 0.27440146 0.22382185]
[ 0.83600451 -1.36510172  0.52909721]
<class 'numpy.ndarray'>
[0.548481   0.27138538 0.22570866]
[ 0

[ 0.75388898 -1.12088902  0.36700004]
<class 'numpy.ndarray'>
[ 0.4414951  -0.00949018  0.35893918]
[ 0.75336691 -1.11941416  0.36604725]
<class 'numpy.ndarray'>
[ 0.44056207 -0.01112524  0.35941512]
[ 0.75284619 -1.11794456  0.36509837]
<class 'numpy.ndarray'>
[ 0.43962891 -0.01275315  0.35988479]
[ 0.75232683 -1.1164802   0.36415338]
<class 'numpy.ndarray'>
[ 0.43869564 -0.01437396  0.36034825]
[ 0.7518088  -1.11502104  0.36321224]
<class 'numpy.ndarray'>
[ 0.43776228 -0.0159877   0.36080555]
[ 0.7512921  -1.11356704  0.36227494]
<class 'numpy.ndarray'>
[ 0.43682885 -0.01759442  0.36125673]
[ 0.75077671 -1.11211817  0.36134146]
<class 'numpy.ndarray'>
[ 0.43589536 -0.01919414  0.36170185]
[ 0.75026263 -1.11067441  0.36041177]
<class 'numpy.ndarray'>
[ 0.43496184 -0.02078691  0.36214095]
[ 0.74974985 -1.1092357   0.35948585]
<class 'numpy.ndarray'>
[ 0.43402831 -0.02237275  0.36257408]
[ 0.74923835 -1.10780203  0.35856368]
<class 'numpy.ndarray'>
[ 0.43309477 -0.02395172  0.36300129]


<class 'numpy.ndarray'>
[ 0.33176561 -0.1643447   0.38261663]
[ 0.69772493 -0.97175249  0.27402757]
<class 'numpy.ndarray'>
[ 0.33091058 -0.16532466  0.38260599]
[ 0.69731151 -0.97073286  0.27342135]
<class 'numpy.ndarray'>
[ 0.33005669 -0.16630054  0.38259299]
[ 0.69689866 -0.96971583  0.27281717]
<class 'numpy.ndarray'>
[ 0.32920394 -0.16727236  0.38257766]
[ 0.69648639 -0.96870139  0.272215  ]
<class 'numpy.ndarray'>
[ 0.32835234 -0.16824012  0.38256002]
[ 0.69607468 -0.96768953  0.27161485]
<class 'numpy.ndarray'>
[ 0.32750189 -0.16920384  0.38254009]
[ 0.69566354 -0.96668023  0.2710167 ]
<class 'numpy.ndarray'>
[ 0.3266526  -0.17016355  0.38251789]
[ 0.69525296 -0.9656735   0.27042053]
<class 'numpy.ndarray'>
[ 0.32580446 -0.17111925  0.38249343]
[ 0.69484294 -0.9646693   0.26982636]
<class 'numpy.ndarray'>
[ 0.32495749 -0.17207096  0.38246674]
[ 0.69443348 -0.96366763  0.26923415]
<class 'numpy.ndarray'>
[ 0.32411169 -0.1730187   0.38243783]
[ 0.69402457 -0.96266847  0.26864391]


[ 0.22979267 -0.26360797  0.36678601]
[ 0.64724527 -0.85578096  0.20853569]
<class 'numpy.ndarray'>
[ 0.22910825 -0.26416313  0.36659161]
[ 0.64688941 -0.85502117  0.20813176]
<class 'numpy.ndarray'>
[ 0.22842518 -0.26471578  0.36639653]
[ 0.6465339  -0.85426286  0.20772896]
<class 'numpy.ndarray'>
[ 0.22774346 -0.26526592  0.36620077]
[ 0.64617873 -0.85350604  0.20732731]
<class 'numpy.ndarray'>
[ 0.22706308 -0.26581358  0.36600434]
[ 0.64582391 -0.85275069  0.20692678]
<class 'numpy.ndarray'>
[ 0.22638404 -0.26635874  0.36580725]
[ 0.64546943 -0.85199682  0.20652738]
<class 'numpy.ndarray'>
[ 0.22570634 -0.26690144  0.3656095 ]
[ 0.6451153  -0.85124441  0.20612911]
<class 'numpy.ndarray'>
[ 0.22502999 -0.26744166  0.36541111]
[ 0.64476151 -0.85049347  0.20573195]
<class 'numpy.ndarray'>
[ 0.22435498 -0.26797943  0.36521207]
[ 0.64440807 -0.84974398  0.20533591]
<class 'numpy.ndarray'>
[ 0.22368131 -0.26851474  0.3650124 ]
[ 0.64405496 -0.84899594  0.20494098]
<class 'numpy.ndarray'>


<class 'numpy.ndarray'>
[ 0.14974573 -0.31858865  0.3369636 ]
[ 0.60241617 -0.76547754  0.16306137]
<class 'numpy.ndarray'>
[ 0.14923325 -0.31887199  0.3367265 ]
[ 0.60210187 -0.76487951  0.16277764]
<class 'numpy.ndarray'>
[ 0.14872196 -0.31915371  0.33648934]
[ 0.60178786 -0.76428246  0.1624946 ]
<class 'numpy.ndarray'>
[ 0.14821186 -0.31943383  0.33625212]
[ 0.60147412 -0.76368639  0.16221227]
<class 'numpy.ndarray'>
[ 0.14770296 -0.31971234  0.33601486]
[ 0.60116067 -0.76309129  0.16193062]
<class 'numpy.ndarray'>
[ 0.14719524 -0.31998925  0.33577756]
[ 0.60084751 -0.76249717  0.16164967]
<class 'numpy.ndarray'>
[ 0.14668871 -0.32026457  0.33554021]
[ 0.60053462 -0.76190402  0.1613694 ]
<class 'numpy.ndarray'>
[ 0.14618336 -0.3205383   0.33530282]
[ 0.60022202 -0.76131184  0.16108982]
<class 'numpy.ndarray'>
[ 0.1456792  -0.32081044  0.33506539]
[ 0.5999097  -0.76072062  0.16081092]
<class 'numpy.ndarray'>
[ 0.14517622 -0.32108101  0.33482792]
[ 0.59959766 -0.76013036  0.1605327 ]


<Figure size 640x480 with 1 Axes>

In [ ]:
# backpropagation example for deep learning in python class.
# with sigmoid activation
#
# the notes for this class can be found at: 
# https://deeplearningcourses.com/c/data-science-deep-learning-in-python
# https://www.udemy.com/data-science-deep-learning-in-python
from __future__ import print_function, division
from builtins import range
# Note: you may need to update your version of future
# sudo pip install -U future

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1)

def forward(X, W1, b1, W2, b2):
    Z = 1 / (1 + np.exp(-X.dot(W1) - b1))
    A = Z.dot(W2) + b2
    expA = np.exp(A)
    Y = expA / expA.sum(axis=1, keepdims=True)
    return Y, Z


# determine the classification rate
# num correct / num total
def classification_rate(Y, P):
    n_correct = 0
    n_total = 0
    for i in range(len(Y)):
        n_total += 1
        if Y[i] == P[i]:
            n_correct += 1
    return float(n_correct) / n_total


def derivative_w2(Z, T, Y):
    N, K = T.shape
    M = Z.shape[1] # H is (N, M)

    # # slow
    # ret1 = np.zeros((M, K))
    # for n in xrange(N):
    #     for m in xrange(M):
    #         for k in xrange(K):
    #             ret1[m,k] += (T[n,k] - Y[n,k])*Z[n,m]

    # # a bit faster - let's not loop over m
    # ret2 = np.zeros((M, K))
    # for n in xrange(N):
    #     for k in xrange(K):
    #         ret2[:,k] += (T[n,k]* - Y[n,k])*Z[n,:]

    # assert(np.abs(ret1 - ret2).sum() < 0.00001)

    # # even faster  - let's not loop over k either
    # ret3 = np.zeros((M, K))
    # for n in xrange(N): # slow way first
    #     ret3 += np.outer( Z[n], T[n] - Y[n] )

    # assert(np.abs(ret1 - ret3).sum() < 0.00001)

    # fastest - let's not loop over anything
    ret4 = Z.T.dot(T - Y)
    # assert(np.abs(ret1 - ret4).sum() < 0.00001)

    return ret4


def derivative_w1(X, Z, T, Y, W2):
    N, D = X.shape
    M, K = W2.shape

    # slow way first
    # ret1 = np.zeros((X.shape[1], M))
    # for n in xrange(N):
    #     for k in xrange(K):
    #         for m in xrange(M):
    #             for d in xrange(D):
    #                 ret1[d,m] += (T[n,k] - Y[n,k])*W2[m,k]*Z[n,m]*(1 - Z[n,m])*X[n,d]

    # fastest
    dZ = (T - Y).dot(W2.T) * Z * (1 - Z)
    ret2 = X.T.dot(dZ)

    # assert(np.abs(ret1 - ret2).sum() < 0.00001)

    return ret2


def derivative_b2(T, Y):
    return (T - Y).sum(axis=0)


def derivative_b1(T, Y, W2, Z):
    return ((T - Y).dot(W2.T) * Z * (1 - Z)).sum(axis=0)


def cost(T, Y):
    tot = T * np.log(Y)
    return tot.sum()


def main():
    # create the data
    Nclass,D = X.shape 
    #D = 2 # dimensionality of input
    M = 5 # hidden layer size
    K = 2 # number of classes

    #X1 = np.random.randn(Nclass, D) + np.array([0, -2])
    #X2 = np.random.randn(Nclass, D) + np.array([2, 2])
    #X3 = np.random.randn(Nclass, D) + np.array([-2, 2])
    #X = np.vstack([X1, X2, X3])

    #Y = np.array([0]*Nclass + [1]*Nclass + [2]*Nclass)
    #N = len(Y)
    ## turn Y into an indicator matrix for training
    #T = np.zeros((N, K))
    #for i in range(N):
        #T[i, Y[i]] = 1
    
    zeros = np.zeros(N*K).reshape(N,K)
    T = np.hstack((targets,zeros))
        
    for i in range(N):
        index_value = T[i,0]
        T[i, int(index_value)] = 1
    T = np.delete(T, 0, axis = 1)

    # let's see what it looks like
    plt.scatter(X[:,0], X[:,1], c=Y, s=100, alpha=0.5)
    plt.show()

    # randomly initialize weights
    W1 = np.random.randn(D, M)
    b1 = np.random.randn(M)
    W2 = np.random.randn(M, K)
    b2 = np.random.randn(K)

    learning_rate = 1e-3
    costs = []
    for epoch in range(1000):
        output, hidden = forward(X, W1, b1, W2, b2)
        if epoch % 100 == 0:
            c = cost(T, output)
            P = np.argmax(output, axis=1)
            r = classification_rate(Y, P)
            print("cost:", c, "classification_rate:", r)
            costs.append(c)

        # this is gradient ASCENT, not DESCENT
        # be comfortable with both!
        # oldW2 = W2.copy()
        W2 += learning_rate * derivative_w2(hidden, T, output)
        b2 += learning_rate * derivative_b2(T, output)
        W1 += learning_rate * derivative_w1(X, hidden, T, output, W2)
        b1 += learning_rate * derivative_b1(T, output, W2, hidden)

    plt.plot(costs)
    plt.show()


if __name__ == '__main__':
    main()