In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
def Standardize_Values(matt,column_index_list):
        for i in range(len(column_index_list)):
            matt[:,column_index_list[i]] = (matt[:,column_index_list[i]] - matt[:,column_index_list[i]].mean())/matt[:,column_index_list[i]].std()
        return matt

In [4]:
data = np.copy(df)
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [5]:
Y = data[:,-1]
Y.shape

(768,)

In [6]:
X = data[:,:-1]

In [7]:
X_standard = Standardize_Values(np.copy(X),[0,1,2,3,4,5,6,7])
X_standard.shape

(768, 8)

In [8]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [9]:
N,D = X.shape

In [10]:
ones = np.array([1]*N).reshape(N,1)
ones.shape
X_standard = np.hstack((X_standard,ones))
N,D = X_standard.shape

In [11]:
W = np.random.randn(D)
W.reshape(1,D)

array([[ 1.26787366, -0.47684781,  0.80976335, -0.03436728, -0.02836842,
        -0.87914762, -0.98741327,  0.30544084, -0.31542372]])

In [12]:
predictions = sigmoid(np.dot(W,X_standard.T))
np.mean(Y == np.round(predictions))

0.4986979166666667

In [13]:
iteration_num = 101
a = 0.001
while iteration_num > 0:
    predictions = sigmoid(np.dot(W,X_standard.T))
    f_prime = np.dot((predictions - Y),X_standard)
    W -= a*f_prime
    print(np.mean(Y == np.round(predictions)))
    iteration_num -= 1
    
    
print(W)

0.4986979166666667
0.5598958333333334
0.5924479166666666
0.6184895833333334
0.6471354166666666
0.66796875
0.69140625
0.70703125
0.71875
0.73046875
0.7408854166666666
0.7421875
0.7526041666666666
0.7643229166666666
0.7630208333333334
0.76171875
0.7643229166666666
0.7682291666666666
0.7734375
0.7708333333333334
0.76953125
0.76953125
0.7721354166666666
0.7721354166666666
0.7734375
0.7760416666666666
0.7786458333333334
0.7786458333333334
0.7786458333333334
0.7799479166666666
0.78125
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.78125
0.78125
0.78125
0.78125
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.78125
0.7838541666666666
0.7838541666666666
0.7838541666666666
0.7838541666666666
0.7838541666666666
0.7838541666666666
0.7838541666666666
0.7838541666666666
0.7838541666666666
0.7825520833333334
0.7825520833333334
0.7825520833333334
0.7825520833333334
0

In [14]:
np.mean(np.round(predictions) == Y)

0.7825520833333334

In [19]:
# using class for diabetes

In [54]:
def optimize_weights(X,Y,iter_num,a):
    N,D = X.shape
    W = np.random.randn(D)
    predictions = sigmoid(np.dot(W,X.T))
    print(np.mean(np.round(predictions) == Y))
    
    for i in range(iter_num):
        predictions = sigmoid(np.dot(W,X.T))
        derivative = np.dot((predictions - Y), X)
        W -= a*derivative
        
    print(W)
    print(np.mean(np.round(predictions) == Y))

In [55]:
X_standard
#feature data from above, alerady standardized

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.46849198,
         1.4259954 ,  1.        ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.36506078,
        -0.19067191,  1.        ],
       [ 1.23388019,  1.94372388, -0.26394125, ...,  0.60439732,
        -0.10558415,  1.        ],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.68519336,
        -0.27575966,  1.        ],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.37110101,
         1.17073215,  1.        ],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.47378505,
        -0.87137393,  1.        ]])

In [56]:
Y
#target data from above

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [58]:
optimize_weights(X_standard,Y,10001,0.0001)

0.4375
[ 0.41480205  1.12354383 -0.25717844  0.00986742 -0.13724672  0.70675625
  0.31296113  0.17474906 -0.87110175]
0.7825520833333334
